kind: ServiceAccount
apiVersion: v1
metadata:
  name: auth-proxy
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.auth-proxy: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"auth-proxy"}}'
